valhalla/thor

src/thor/astarheuristic.cc
src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/edgelabel.cc
src/thor/pathalgorithm.cc
src/thor/pedestriancost.cc
valhalla/thor/astarheuristic.h
valhalla/thor/autocost.h
valhalla/thor/bicyclecost.h
valhalla/thor/dynamiccost.h
valhalla/thor/edgelabel.h
valhalla/thor/pedestriancost.h

Update costing to not allow using edges that are "not_thru" unless near the destination. 
@kevinkreiser @gknisely @dgearhart

Updates to use not_thru flags

---

src/thor/edgestatus.cc
src/thor/pathalgorithm.cc
valhalla/thor/edgestatus.h
valhalla/thor/pathalgorithm.h

Much faster. Some other cleanup of variable naming.
@kevinkreiser @gknisely @dgearhart

unordered_map

---

src/thor/trippathbuilder.cc

Debug update

---

Makefile.am
src/thor/autocost.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
valhalla/thor/autocost.h
valhalla/thor/bicyclecost.h
valhalla/thor/costfactory.h
valhalla/thor/pedestriancost.h

Fixed a couple issues with PathAlgorithm (was calling wrong A* method!) and fix some pure virtual methods in Bicycle and Auto costing.
@dgearhart @gknisely @kevinkreiser

Add a CostFactory and Get auto routes to work

---

src/thor/trippathbuilder.cc

@kevinkreiser  @dnesbitt61 @gknisely

Updated test output

---

src/thor/trippathbuilder.cc

Removed edgeinfo debug - just printing the edge names

---

src/thor/pathtest/pathtest.cc
src/thor/pedestriancost.cc
valhalla/thor/pedestriancost.h

@kevinkreiser @dgearhart @dnesbitt61
pathtest now takes a route type
./pathtest -o 40.051602,-76.321168 -d 40.043771,-76.323099 -t pedestrian conf/pbf2graph.json

Favor walkways paths gk

---

src/thor/pathtest/pathtest.cc
src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

@dgearhart @kevinkreiser @gknisely

Start hooking in TripPath (protocol buffer).

---

src/thor/trippathbuilder.cc

Added some attributes for odin.  @kevinkreiser @dgearhart @dnesbitt61

added some attributes to trip_edge.

---

src/thor/trippathbuilder.cc

added shape, shape offsets, and headings.

---

src/thor/pathtest/pathtest.cc
src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

Also, passing TripPath into builder

Updates becuase leg was removed from TripPath

---

src/thor/pathtest/pathtest.cc

changed to use DirectionsBuilder

---

src/thor/pathtest/pathtest.cc

Updated to process the returned TripDirections

---

src/thor/pathalgorithm.cc

Improves performance by almost 50% on PA test route.

Key fix to shortcut logic. Avoids superseded edges better.

---

src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

@kevinkreiser @dgearhart @dnesbitt61 
Can remove couts after the DE bug is fixed.

Gk connected edges

---

src/thor/trippathbuilder.cc

use graphtile for now until we need to save node data.

---

src/thor/trippathbuilder.cc

Some fixes to connected edge logic and how to determine opposing edgeto the incoming path edge at a node. Add a constant for the offset distance for finding heading (and use km as the method requires).

Connected Edges fixes and heading fix

---

src/thor/pathtest/pathtest.cc

start testing directions.Build

---

src/thor/trippathbuilder.cc

fixed shape bug.  Was flipped.
@kevinkreiser @dgearhart @dnesbitt61

shape flipped.

---

src/thor/trippathbuilder.cc

fixed heading issues when shape is flipped.

---

src/thor/astarheuristic.cc
src/thor/autocost.cc
src/thor/pathalgorithm.cc
src/thor/pedestriancost.cc
src/thor/trippathbuilder.cc
valhalla/thor/astarheuristic.h
valhalla/thor/edgelabel.h

Depends on midgard, baldr, mjolnir, and new data

Use meters for distance.

---

src/thor/pathtest/pathtest.cc

removed call to BuildSimple

---

src/thor/trippathbuilder.cc

set more odin flags.

---

src/thor/astarheuristic.cc
src/thor/bicyclecost.cc
valhalla/thor/astarheuristic.h

Needs a round of testing and also some config/options methods. Defer this until we start working on more extensive costing plugin development.

Initial bicycle costing

---

src/thor/trippathbuilder.cc

set the heading for connected edges.

---

src/thor/trippathbuilder.cc

Added road class assignment

---

src/thor/trippathbuilder.cc

@gknisely @dnesbitt61 @kevinkreiser

Updates for road class

---

conf/pbf2graph.json
src/thor/pathtest/pathtest.cc

add logging subconfig

---

src/thor/pathalgorithm.cc

May want to do this in Loki instead, but adding here for now.

Do not allow transition edges at origin. 

---

src/thor/autocost.cc
src/thor/pathalgorithm.cc

Only set has_shortcuts if one is actually allowed/taken. This makes a huge difference and fixes routes I was pondering for much too long.

Fix shortcuts!

---

src/thor/trippathbuilder.cc

@gknisely @kevinkreiser @dnesbitt61

Assign exit info

---

src/thor/trippathbuilder.cc

fixed kBranch typo.

---

Makefile.am
src/thor/formlocalpath.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
src/thor/trippathbuilder.cc
valhalla/thor/pathalgorithm.h

Update to use edgeinfo_offset for directed edges.
Update timing in pathtest to not do CPU clock usage but use std::chrono:high_resolution_clock so we get elapsed time (include I/O wait).

Add initial code to form path on local level

---

src/thor/edgestatus.cc
src/thor/pathalgorithm.cc

graphid refactor compatibility

---

scripts/batch.sh
src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/pathtest/pathtest.cc
src/thor/pedestriancost.cc
valhalla/thor/dynamiccost.h

this route used to go the wrong way on a oneway street but doesnt anymore:
kkreiser@klaptop:~/sandbox/valhalla/thor$ pathtest -o "40.043138,-76.302218" -d "40.043203, -76.300169" -t auto --config conf/valhalla.json 
2015/02/05 17:56:39.867591 [INFO] routetype: auto
2015/02/05 17:56:39.875967 [INFO] Location Processing took 8 ms
2015/02/05 17:56:39.876006 [INFO] Sizeof GraphTileHeader = 80
2015/02/05 17:56:39.876092 [INFO] PathAlgorithm Construction took 0 ms
2015/02/05 17:56:39.878370 [INFO] PathCost = 48.690002  Iterations = 166
2015/02/05 17:56:39.878431 [INFO] PathAlgorithm GetBestPath took 2 ms
2015/02/05 17:56:39.878586 [INFO] TripPathBuilder took 0 ms
2015/02/05 17:56:39.879126 [INFO] PathAlgorithm Clear took 0 ms
2015/02/05 17:56:39.879915 [INFO] PathCost = 48.690002  Iterations = …

update thor to make use of edge filtering in location searches

---

src/thor/trippathbuilder.cc

TripPath_Exit to TripPath_Sign updates

---

src/thor/trippathbuilder.cc

Updates for exit number list

---

scripts/batch.sh

Make the directory name smaller and easier to read

---

scripts/batch.sh

Removed colon from output line - to make copy paste easier

---

src/thor/formlocalpath.cc
valhalla/thor/pathalgorithm.h

Working version (at least on a couple test routes). Still need to update pathalgorithm.cc to use it and figure out performance impact.

Recover shortcuts on local path

---

src/thor/pathalgorithm.cc
src/thor/trippathbuilder.cc
valhalla/thor/pathalgorithm.h

there are cases where to get from a to b you basically have to go around the block and end on the same edge you begin on. the alogrithm doesnt let you touch the same edge twice so this pr works around that, and fixes a bittle part of the shape trimming stuff for partial distance.

allow for the loop route!

---

src/thor/pathalgorithm.cc
src/thor/trippathbuilder.cc
valhalla/thor/pathalgorithm.h

before these changes, this route was not the shortest route:
with these changes we make sure to consider the shorter alternative as the proper shortest path:
it works by keeping track of what destination edges you've found and waiting until you've either, visited all edges in the set of possibly destination edges or (more likely) consider an edge which is has a larger cost to get to than the destination edge that has already been found.

take the shortest path even if its basically a crap shoot

---

src/thor/trippathbuilder.cc

Set internal_intersection

---

src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/pedestriancost.cc

@dgearhart @kevinkreiser @dnesbitt61

added logic to check for access at nodes for each type of costing.

---

src/thor/bicyclecost.cc
src/thor/pathalgorithm.cc

Also sneak in some variable declaration changes that should make Kevin happy.

Bicycle costing changes

---

src/thor/trippathbuilder.cc

- when a shortcut edge was not recovered on the local level the tile was on the incorrect level. Use the start node (and get the tile of the start node) rather than saving nodeinfo and using the prior tile

Fix exception when recovering shortcut edge on local level fails

---

scripts/demo_routes.txt
scripts/internal_edge_routes.txt

Added test files

---

src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

added gate and tollbooth.

---

src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

removed from AddTripEdge

---

src/thor/adjacencylist.cc
src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/edgestatus.cc
src/thor/pathalgorithm.cc
src/thor/pedestriancost.cc
valhalla/thor/adjacencylist.h
valhalla/thor/dynamiccost.h
valhalla/thor/edgestatus.h

Make sure mincost and current cost align to buckets.

Use integer sizes for Adj list buckets

---

scripts/doubly_digitized_uturn_routes.txt
scripts/pencil_point_uturn_routes.txt
scripts/turn_channel_routes.txt

Added route request files for turn channels, doubly digitized u-turns, and pencil point u-turns

---

src/thor/pathalgorithm.cc

Was leading to truncation errors in precision of costing.

Fix currentcost - should have been float! 

---

src/thor/adjacencylist.cc
src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/edgelabel.cc
src/thor/pathalgorithm.cc
src/thor/pedestriancost.cc
valhalla/thor/dynamiccost.h
valhalla/thor/edgelabel.h

Need to recreate data so the mjolnir fix that properly sets opp_local_idx on shortcut edges gets added.

Use opp_local_idx for Uturn determination.

---

src/thor/autocost.cc
src/thor/dynamiccost.cc
src/thor/edgelabel.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
valhalla/thor/dynamiccost.h
valhalla/thor/edgelabel.h
valhalla/thor/hierarchylimits.h

Also add a simple check to make sure route is converging and to return failure if not. Has to go 500K iterations without converging (pretty conservative!) but helps limit a long walking route that fails - so it fails sooner.

Add method to relax hierarchy limits and allow multiple passes

---

scripts/demo_routes.txt
src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

Added AddTripIntersectingEdge to store the local intersecting edge information

---

src/thor/autocost.cc
src/thor/bicyclecost.cc
src/thor/dynamiccost.cc
src/thor/pathalgorithm.cc
src/thor/pedestriancost.cc
valhalla/thor/dynamiccost.h

First cut in autocost.
stop_impact * turncost + maneuverpenalty

Transition cost

---

src/thor/adjacencylist.cc
valhalla/thor/adjacencylist.h

Use static_cast in a couple places where old style cast was present

Add inverse of bucketsize so we can avoid division

---

conf/valhalla.json

added country_crossing_factor and avoid_country_crossings

---

conf/valhalla.json
src/thor/pathtest/pathtest.cc

Change costing to costing_options

---

src/thor/trippathbuilder.cc

paired with @gknisely 
@dnesbitt61 @kevinkreiser

Added location information to TripPath

---

src/thor/trippathbuilder.cc

Changed StopType to Type under Location

---

src/thor/trippathbuilder.cc

fixed missing state

---

conf/valhalla.json

removed country crossing flag.

---

src/thor/pathtest/pathtest.cc

Added DirectionsOptions

---

src/thor/pathtest/pathtest.cc

Updated display of length and time

Used the summary length and time populated in odin

---

.gitignore
Makefile.am
src/thor/citytest/citytest.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
src/thor/trippathbuilder.cc
valhalla/thor/pathalgorithm.h
valhalla/thor/pathinfo.h
valhalla/thor/trippathbuilder.h

Updates to add travel mode and elapsed time into trip path

---

src/thor/citytest/citytest.cc
src/thor/edgestatus.cc
src/thor/pathalgorithm.cc
test/edgestatus.cc
valhalla/thor/edgestatus.h
valhalla/thor/pathalgorithm.h

Simplify code by adding the edge label index to the EdgeStatus.

Remove adj list map

---

src/thor/trippathbuilder.cc

Added drive_on_right assignment to trip path.

---

src/thor/trippathbuilder.cc

Example info of route from PA to MD:
ADMIN 0: country_code=US | country_text=United States of America | state_code=PA | state_text=Pennsylvania | start_dst= | end_dst=
ADMIN 1: country_code=US | country_text=United States of America | state_code=MD | state_text=Maryland | start_dst= | end_dst=

Added assignment of admin to the trip path

---

src/thor/pathalgorithm.cc

(so costing can exclude paths where max walking distance is exceeded).
Depends on sif changes.

Add walking distance to edge label

---

src/thor/pathalgorithm.cc
valhalla/thor/pathalgorithm.h

For now just switches between transit and pedestrian TravelModes. Also need to add transfer costs.
Depends on sif updates

Initial multimodeal path algorithm Accepts an array of costing methods.

---

conf/valhalla.json
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc

Use costing=multimodal to populate array of costing methods per mode and use GetBestPathMM.

Updates to GetBestPathMM and pathtest

---

src/thor/service.cc
src/thor/trippathbuilder.cc

most of this is whitespace but some of it isn't sorry for the hard to read diff. i basiclally reapplied diffs from 7 versions ago

a few fixes for trippath builder and a log message

---

src/thor/service.cc

requires prime_server reinstall

small change for primeserver logging

---

src/thor/pathalgorithm.cc
valhalla/thor/pathalgorithm.h

Also add a method shared between the 2 BestPath algorithms to check if the new path to a temporarily labeled edge is lower cost than prior path.

Multimodal updates

---

src/thor/pathalgorithm.cc

Reuse of the tile parameter was an issue - if the end node crossed into a new tile it updated the tile and then tried to read departures from the wrong tile. Also the prior stop Id logic was changed to track the prior stop id until a new stop is entered.

Fix departure lookup for MulitModal

---

src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

Add block Id to trip edge. Update so that the arrive time is time arriving at current node and departure time is time departing from current node.

Transit departure / arrival time updates

---

src/thor/pathalgorithm.cc

log message stats reformat

---

scripts/nyc_transit_routes.txt

created nyc transit routes file

---

src/thor/pathalgorithm.cc

Remove walking distance from regular path computation.

---

src/thor/pathalgorithm.cc
valhalla/thor/pathalgorithm.h

Modify arterial hierarchy distance from destination based on route length and (later) density at the destination.

Add ModulateHierarchyLimits

---

Makefile.am
src/thor/multimodal.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
src/thor/service.cc
valhalla/thor/pathalgorithm.h

Add method to test if destination cannot be reached. Does a shortest path test from the destination to see if a transit stop can be reached within the max mode distance at the destination (currently assumes pedestrian). This will prevent long search times on transit routes where there is no stop near the destination. Later when other travel modes are added the method will have to be extended.
Thor service and pathtest now do this check.

Separate multimodal code

---

src/thor/pathalgorithm.cc

needs to be remainder of cost along destination edge and subtract this from the edge_label cost since cost
in the edge label is to the end of the destination edge.

Fix destination partial distance 

---

Makefile.am
src/thor/bidirectional_astar.cc
src/thor/citytest/citytest.cc
src/thor/multimodal.cc
src/thor/pathalgorithm.cc
src/thor/pathtest/pathtest.cc
src/thor/service.cc
valhalla/thor/bidirectional_astar.h
valhalla/thor/pathalgorithm.h

Derived bidirectional A* and multimodal from PathAlgorithm and create common interface for GetBestPath.
Use bidirectional A* for pedestrian routes > 10km.

Add bidirectional A*

---

scripts/batch.sh
scripts/failCount.sh
scripts/run_city_routes.sh
src/thor/pathtest/pathtest.cc

* run_city_routes.sh runs all all routes in city_to_city
* failCount.sh calculates a failure rate for output directories in pwd

Created two short scripts

---

src/thor/pathtest/pathtest.cc

Example:
2015/07/22 17:47:27.851242 [NARRATIVE] 2: Turn right onto North Prince Street/US 222. Continue on US 222. | 3.9 mi
2015/07/22 17:47:27.851259 [NARRATIVE]    VERBAL_ALERT: Turn right onto North Prince Street.
2015/07/22 17:47:27.851275 [NARRATIVE]    VERBAL_PRE: Turn right onto North Prince Street,US 222.
2015/07/22 17:47:27.851291 [NARRATIVE]    VERBAL_POST: Continue on US 222 for 3.9 miles.

 Added verbal instructions to the narrative output

---

src/thor/pathalgorithm.cc

Fix bug - wrong tile used for directed edge.

---

src/thor/bidirectional_astar.cc
src/thor/pathalgorithm.cc

Set restrictions on the origin edges so turn restrictions are honored off the initial edge.

Fix turn restriction bug

---

.gitignore
Makefile.am
src/thor/pathalgorithm.cc
src/thor/timedistance_test/timedistance_test.cc
src/thor/timedistancematrix.cc
valhalla/thor/timedistancematrix.h

Start with OneToMany method. Added a test application and compared a simple case against individual routes. More testing to do, but a good start.

Initial time+distance matrix support.

---

src/thor/bidirectional_astar.cc
src/thor/pathtest/pathtest.cc
src/thor/timedistancematrix.cc
valhalla/thor/timedistancematrix.h

Fix bidirectional edge costing - should use the opposing directed edge. In most cases the costing is the same using either directed edge, but with weighted grade the costing can be different.

Complete the many to One time distance matrix method

---

Makefile.am
src/thor/adjlistbenchmark/adjlistbenchmark.cc

Also validate the order and ensure EmptyOverflow is called.

Update adjacency list benchmark 

---

src/thor/timedistancematrix.cc
valhalla/thor/timedistancematrix.h

So that you can use the cost threshold to control the search range.

Customize cost threshold in TimeDistanceMatrix constructor

---

src/thor/adjacencylist.cc
valhalla/thor/adjacencylist.h

Update Bucket method to handle 3 cases (< currentbucket, within bucket range, or overflowbucket) and use in Add method and also to simplify the DecreaseCost method.

Replace list with deque. Slight performance improvement.

---

src/thor/astarheuristic.cc
src/thor/bidirectional_astar.cc
src/thor/edgestatus.cc
src/thor/multimodal.cc
src/thor/pathalgorithm.cc
src/thor/timedistancematrix.cc
test/edgestatus.cc
valhalla/thor/astarheuristic.h
valhalla/thor/edgestatus.h
valhalla/thor/timedistancematrix.h

Reserve size for the unordered_map (performance improvement on long routes).. Update EdgeStatus to use the strongly typed enum. Add convenience method to get the heuristic and distance in one call.

Allocate size for EdgeStatus

---

src/thor/pathtest/pathtest.cc

Updated the default language tag

---

src/thor/pathtest/pathtest.cc

Behaves like the service URLs now.

Use request JSON to override config options

---

src/thor/pathalgorithm.cc

Can lead to missing the proper connection if the shortcut is too long. Fixes issue #245

Skip long shortcut edges based on distance from the destination.

---

src/thor/trippathbuilder.cc

Use else if for the node type settings.

Save the nodeinfo so we don't have to get it from the tile. 

---

src/thor/service.cc

- split out trip_path and matrix logic
- merged/moved Dave's Thor updates from master into get_trip_path
example one_to_many  request: 
http://localhost:8002/matrix?json={%22locations%22:[{%22lat%22:40.744014,%22lon%22:-73.990508},{%22lat%22:40.739735,%22lon%22:-73.979713},{%22lat%22:40.752522,%22lon%22:-73.985015},{%22lat%22:40.750117,%22lon%22:-73.983704},{%22lat%22:40.750552,%22lon%22:-73.993519}],%22matrix_type%22:%22many_to_one%22,%22costing%22:%22auto%22}
NOTE: Won't merge until next week after code freeze.

Time Distance Matrix Logic added to Thor Service

---

src/thor/service.cc
src/thor/timedistancematrix.cc
valhalla/thor/timedistancematrix.h

look into serialization bug, fix a few small things with unit parsing

---

src/thor/service.cc
src/thor/timedistancematrix.cc
valhalla/thor/timedistancematrix.h

Also changed input_locations to just locations so that it's consistent with routing.  Will update docs as well.

added units logic to return either mi or km for matrix

---

src/thor/bidirectional_astar.cc
src/thor/timedistancematrix.cc
valhalla/thor/bidirectional_astar.h

Fix adding destinations (last commit broke the oneway destination edge case). Support hierarchies so we can apply to auto routes.

Add candidate connections so the least cost path is properly found. 

---

scripts/batch.sh

paired with @kevinkreiser to fix the stats results order

Fixed the order of the stats results

---

src/thor/trippathbuilder.cc

set_assumed_schedule is now set as needed.

populating assumed flag.

---

src/thor/multimodal.cc
src/thor/trippathbuilder.cc

added check to see if the date that was inputed is before the tile_creation date    if so, forced to use assumed transit schedule

added check to see if the date that was inputed is before the tile_creation date

---

scripts/dependencies.sh
scripts/install_yml_cpp.sh

@kevinkreiser does look good to you?

add yaml parser dependency

---

src/thor/bidirectional_astar.cc
src/thor/multimodal.cc
src/thor/pathalgorithm.cc
src/thor/service.cc
valhalla/thor/bidirectional_astar.h
valhalla/thor/pathalgorithm.h

date time is now set on the origin in set_origin if we are starting at the current time.

date time fix

---

src/thor/bidirectional_astar.cc
src/thor/pathalgorithm.cc

Reuse nodeinfo (end node of an origin directed edge) to set the origin timezone rather than a special case at the start to get an edge, then its end node.

Simplify setting the origin timezone within SetOrigin

---

src/thor/bidirectional_astar.cc

in the constructor/emplace calls. Separate downward transition logic and disable for now - see if that is what we want for driving routes. Use sort cost vs. cost as the factor for which path (forward or reverse) to expand. This PR depends on sif PR.

Update edge label to have transition cost

---

src/thor/bidirectional_astar.cc

This solves some issues that occurred in auto routes in less urban areas.

Back to using distance to destination in the StopExpanding method

---

src/thor/service.cc

-Added a many-to-many long request threshold in the config since this differs greatly from other route requests or the other 2 types of matrix requests

Matrix logging updates

---

src/thor/multimodal.cc

added GetModeWeight from costing.  
Added call to UseMaxMultiModalDistance.  
Added logic for GetMaxTransferDistanceMM.

distance and weight updates.

---

configure.ac
scripts/install_service_deps.sh
src/thor/service.cc

locked prime_server version to 0.3.2 and added DNT check for long_requests

Do Not Track - Conditional Logging

---

src/thor/trippathbuilder.cc

Ferry example://
long_name": "Staten Island Ferry",
"operator_url": "http://nyc.gov/dot",
"onestop_id": "r-dr5r7-statenislandferry",
**"type": ​4,**
"short_name": "Staten Island Ferry",
"color": ​16745264,
Subway or metro example://
"operator_url": "http://web.mta.info/",
"long_name": "Broadway Local",
"onestop_id": "r-dr5r-r",
**"type": ​1,**
"short_name": "R",
"color": ​16567306,
Rail example:// 
"long_name": "Harlem",
"operator_url": "http://www.mta.info/mnr",
"onestop_id": "r-dr7-harlem",
**"type": ​2,**
"short_name": "Harlem",
"color": ​14758,
Bus example://
"operator_url": "http://web.mta.info/",
"long_name": "Bay Ridge - Kings Plaza",
"onestop_id": "r-dr5rh-b9",
**"type": ​3,**
"short_name": "B9",
"color": ​15611182,

send the transit type to odin.

---

docs/path-algorithm.md

Still more details to fill in but this gives an overview.

First draft of Thor path algorithm description.

---

src/thor/trippathbuilder.cc

Updated transit travel mode from TripPath_TravelMode_kPublicTransit to TripPath_TravelMode_kTransit

---

src/thor/bidirectional_astar.cc
valhalla/thor/bidirectional_astar.h

Moves code out of the main method to make a bit more readable.

Add methods to CheckForwardConnection and CheckReverseConnection

---

src/thor/matrix.cc
src/thor/optimized_path.cc

This updates calls the new CostMatrix::SourceToTarget function for all matrix and optimized requests to make response times faster

Matrix & Optimized now using CostMatrix

---

src/thor/costmatrix.cc
valhalla/thor/costmatrix.h

Also protect against failure to break out of loop - set a max number of iterations and log an error if this is reached.

Extend default threshold for CostMatrix.

---

src/thor/optimized_path.cc

Return will be 400: Location N is unreachable.

Throw exception if a location is unreachable

---

src/thor/bidirectional_astar.cc
src/thor/costmatrix.cc
src/thor/isochrone.cc
src/thor/multimodal.cc
src/thor/pathalgorithm.cc
src/thor/service.cc
src/thor/timedistancematrix.cc
src/thor/trip_path.cc
src/thor/trippathbuilder.cc
test/thor_service.cc

this goes along with valhalla/baldr#254

conform to refactor of connectivity map and path location

---

valhalla/thor/pathalgorithm.h

(this was replaced by logic in loki).

Remove unused update_destinations method signature 

---

src/thor/isochrone.cc

Adjust the bounds to allow more grid tiles in longitude than latitude (based on meters per degree of longitude at the first origin location's latitude).

Change to use a grid size in meters. 

---

src/thor/isochrone.cc

This is so we don't miss any tiles along the shape (without this can get gaps and disjoint contours). Also check if opposing directed edge has been settled - if so can skip marking tiles along the edge. Seems to be about a 30% speedup.

Use the tile Intersect method 

---

src/thor/isochrone.cc
valhalla/thor/isochrone.h

Create a couple of common methods to simplify code a bit.

Add multimodal isocrhone support.

---

src/thor/isochrone.cc
src/thor/matrix.cc
src/thor/optimized_path.cc
src/thor/service.cc
src/thor/trip_path.cc
test/thor_service.cc
valhalla/thor/isochrone.h
valhalla/thor/service.h

this also removes the one long request parameter for matrix

add isochrone response and compute them in minutes not seconds

---

src/thor/bidirectional_astar.cc
src/thor/costmatrix.cc
src/thor/isochrone.cc
valhalla/thor/isochrone.h

Time to get to a location.
Use new GraphTile GetOpposingEdgeId method.

Add reverse isochrone

---

Makefile.am
src/thor/astar.cc
src/thor/bidirectional_astar.cc
src/thor/multimodal.cc
src/thor/trafficalgorithm.cc
valhalla/thor/astar.h
valhalla/thor/bidirectional_astar.h
valhalla/thor/multimodal.h
valhalla/thor/pathalgorithm.h
valhalla/thor/service.h
valhalla/thor/trafficalgorithm.h

Add new AStarPathAlgorithm (was the existing PathAlgorithm). Derive multimodal, bidirectional, traffic path algorithms from either the base PathAlgorithm or from AStarPathAlgorithm. Fixes #193

Make PathAlgorithm pure virtual.

---

valhalla/thor/costmatrix.h

since that is now the primary class for matrix computations.

Move TimeDistance struct into CostMatrix 

---

src/thor/service.cc

- Updates to get_costing to no longer override the costing options

Costing option function updates

---

src/thor/service.cc
src/thor/trace_route_action.cc
valhalla/thor/service.h

Refactored to create factory in trace_actions and fixed leak by deleting pointer

Trace actions

---

src/thor/trippathbuilder.cc

Refactored node type

---

src/thor/trippathbuilder.cc
valhalla/thor/trippathbuilder.h

id, base_data_id, weighted_grade, max_upward_grade, and max_downward_grade

Assigned the following edge attributes:

---

src/thor/service.cc
valhalla/thor/service.h

Removed unused sources and targets

Clean up shape

---

src/thor/trace_attributes_action.cc
src/thor/trace_route_action.cc

- also refactored to use Enhanced Trip Path

Added Exact Match Flag for Trace Route & Attributes

---

src/thor/service.cc
src/thor/trace_attributes_action.cc
src/thor/trace_route_action.cc
valhalla/thor/service.h

also changed action="only" & "none" for filter.attributes to be "include" & "exclude"

Throw exception when invalid shape_match

---

src/thor/trace_attributes_action.cc

Changed default action to enable all attributes if no filter is supplied

---

src/thor/trace_attributes_action.cc
src/thor/trippathbuilder.cc

Updated to use the TripPath Surface enumeration

---

src/thor/trace_attributes_action.cc

Fixed travel mode and type

---

src/thor/isochrone_action.cc
src/thor/matrix_action.cc
src/thor/optimized_route_action.cc
src/thor/route_action.cc
src/thor/service.cc
src/thor/trace_attributes_action.cc
src/thor/trace_route_action.cc
src/thor/trippathbuilder.cc
valhalla/thor/service.h

Changes to address these issues:
valhalla/valhalla#8
valhalla/valhalla#9

API Logging / Logstash Updates
