valhalla/thor

src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/pathalgorithm.cc, src/thor/pathtest/pathtest.cc, src/thor/pedestriancost.cc, valhalla/thor/autocost.h, valhalla/thor/bicyclecost.h, valhalla/thor/costfactory.h, valhalla/thor/dynamiccost.h, valhalla/thor/pathalgorithm.h, valhalla/thor/pedestriancost.h
this moves around a bunch of code but properly sets up the factory so that the caller doesnt have to know about the underlying implementation. the way it works is:
a user of the factory makes a factory object templated by the base class of the type of objects you want the factory to produce
you then register the various objects the factory can produce by sending the factory function pointers (callbacks) to methods that can create objects that derive from the templated base class above
the function pointers basically just point to the constructors of the pimpl for each heuristic
we should at some point add sending a boost ptree to these so as to be able to configure each ones individual options
=> fix up factory for use in service

src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/pedestriancost.cc
Pedestrian and bicycle never allow upward transitions (and thus should never even see downward transitions).
Auto - allow upward transitions until close to the destination and downward transitions only when near the destination. Need to add some tuning and logic based on which level currently on but this at least allows some verification of the graph hierarchy. Seems to transition up and down levels, but without shortcut edges there is a slight performance loss.
=> Simple hierarchy access rules

src/thor/autocost.cc, src/thor/edgelabel.cc, src/thor/pathalgorithm.cc, valhalla/thor/edgelabel.h
Logic to transition up/down levels for auto routes and to limit expansion to improve performance. Distances and counts are currently hard-coded (for testing) - later will want config values and probably multi-pass relaxing of values if route fails.  Large performance improvement - still need to incorporate shortcut edges.
=> Initial hierarchy transitioning

src/thor/trippathbuilder.cc
Still need a way to find the opposing edge to the incoming edge when a level transition has occurred.
=> Fix nodeinfo when transition up/down a level.

src/thor/pathalgorithm.cc, valhalla/thor/adjacencylist.h
Update comments in AdjacencyList. Add pathcost and iteration count as Log info in FormPath. This is good info for making sure shortcuts and costs are making sense.
=> Comment and log updates

src/thor/trippathbuilder.cc, valhalla/thor/trippathbuilder.h
Change to access exits by directed edge index. Only store them if the directed edge exit flag is set.
=> TripPathBuilder Update for Exit Signs

src/thor/pathalgorithm.cc, src/thor/trippathbuilder.cc
this pr fixes a bunch of edge cases with partial distance and trivial pathes. if you start and end on the same link (and you are traveling in the right direction) the shape should be correct. it also fixes routes that end or start on nodes in terms of their shape (used to have duplicated points).
it doesnt fix loops, it doesnt fix pathfinding taking a longer route because it encounters the one destination edge first but has a worse partial distance than would have been if we waited to find the other edge with smaller partial distance. these will have to wait for another pr.
=> partial distance and path finding edge cases

src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/edgelabel.cc, src/thor/pathalgorithm.cc, src/thor/pedestriancost.cc, valhalla/thor/dynamiccost.h, valhalla/thor/edgelabel.h
Simple turn restrictions (one edge to another) are now handled. The left turn from McGovern Ave to Manheim Ave (Jordan's Curve) are properly avoided.
=> Add simple turn restrictions

Makefile.am, src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/dynamiccost.cc, src/thor/pathalgorithm.cc, src/thor/pedestriancost.cc, valhalla/thor/dynamiccost.h, valhalla/thor/hierarchylimits.h, valhalla/thor/pathalgorithm.h
Structure that holds limits per level and does simple checks to see if expansion is allowed or transition is allowed. This allowed costing to be simplified. Next step is to hook in config settings to allow control of the limits and also allow multi-pass routes (e.g. if the first try of a route fails can increase limits).
=> Add HierarchyLimits

src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/dynamiccost.cc, src/thor/pathalgorithm.cc, src/thor/pathtest/pathtest.cc, src/thor/pedestriancost.cc, valhalla/thor/autocost.h, valhalla/thor/bicyclecost.h, valhalla/thor/costfactory.h, valhalla/thor/dynamiccost.h, valhalla/thor/hierarchylimits.h, valhalla/thor/pathalgorithm.h, valhalla/thor/pedestriancost.h
There are default hierarchy limits and now they can be overriden with property tree config. The plumbing to allow other costing options to be set/changed is also in place, though none are being used.
=> Add property tree config to costing and use it for HierarchyLimits

src/thor/autocost.cc, src/thor/pathalgorithm.cc
Need to evaluate if we need the code that prevents taking shortcuts near destination - but left in for now.
=> Shortcuts - moved code out of autocost into pathalgorithm. 

src/thor/autocost.cc, src/thor/bicyclecost.cc, src/thor/dynamiccost.cc, src/thor/edgelabel.cc, src/thor/pathalgorithm.cc, src/thor/pedestriancost.cc, valhalla/thor/dynamiccost.h, valhalla/thor/edgelabel.h, valhalla/thor/pathalgorithm.h
Update the costing model. Splits EdgeCost from TransitionCost (intersection/turn cost). Requires a Cost structure to be returned with both cost and seconds so we can handle time/schedules. Split out hierarchy transition edges so they either get skipped or added to the adjacency list (no need to go through other logic since they have no length).
=> Costing Updates

src/thor/pathalgorithm.cc
so we only skip edges superseded by a matching shortcut edge.
=> Use shortcut mask rather than bool values

conf/valhalla.json, src/thor/autocost.cc, src/thor/dynamiccost.cc, src/thor/pathtest/pathtest.cc, src/thor/pedestriancost.cc, valhalla/thor/dynamiccost.h, valhalla/thor/hierarchylimits.h
Set default options, allow config JSON / property tree to override these. Added a method that can disable highway hierarchy level - need to test and see if htis is what we need to do in regions where highway hierarchy is unconnected/incomplete.
=> Costing - auto and pedestrian updates for pt parsing

src/thor/pathalgorithm.cc
Really wanted the localedgeidx of the directed edge. This fixes maneuver penalties on upper hierarchies.
=> Remove index from TransitionCost.

.gitignore, Makefile.am, circle.yml, conf/valhalla.json, configure.ac, m4/ax_boost_thread.m4, scripts/install_service_deps.sh, src/thor/service.cc, src/thor/thor_service.cc, valhalla/thor/service.h
two things are added here, a binary that makes use of the thor service layer code, and the thor service layer code with is part of the thor library. it makes use of all the prime_server zmq deps but its part of the library so the simple server in tyr can just use it. this way the same code will be run regardless of in production or testing on our local machines
for thor it was really straight forward, grab some info out of the request that loki passes on to us. run the route, serialize the protobuf bytes (and the original request) onto odin.
=> first draft of thor service layer

src/thor/pathalgorithm.cc, src/thor/trippathbuilder.cc
Destinations at a node need the incoming edge, not the outgoing. This fixes the destination edge list such that trivial routes ending at a node now work.
=> Fix trivial routes ending at a node

scripts/batch.sh, src/thor/pathtest/pathtest.cc
Now when pathtest is run some statistics about the route are gathered. They are logged after the narrative and when pathtest is run using batch.sh the statistical output from each path is saved to statistics.csv
The various fields in the csv are as follows:
orgLat, orgLng, destLat, destLng, success, #Passes, runtime, trip time, length, arcDistance, #Manuevers
=> Stastics for pathtest 

src/thor/edgestatus.cc, src/thor/multimodal.cc, src/thor/pathalgorithm.cc, valhalla/thor/edgestatus.h
Calling Set again was corrupting the index. This didn't matter with forward A*, but need to retain the index in bidirectional A*.
=> Add an Update method for EdgeStatus.

src/thor/pathtest/pathtest.cc
Added two flags that can be passed to PathTest:
* `--connectivity` - Builds a connectivity map before running the path algorithms
* `--multi-run N` - Runs the path algorithm N additional times after the first run to demonstrate caching effects
__Note__ that the default behavior of the program has changed since these both ran on every execution prior to this update.
=> Added program options for connectivity map and multi run

src/thor/citytest/citytest.cc, src/thor/pathalgorithm.cc, src/thor/pathtest/pathtest.cc, src/thor/service.cc, valhalla/thor/pathalgorithm.h
Simplify assignment of mode.
Update pathtest to store correct elapsed time on failure. List destinations to see if marked as unreachable.
Log failures due to non-convergence towards destination.
=> Use mode from costing

src/thor/trippathbuilder.cc
fixed bug where endnode was in another tile and we were trying to get…the admin.  Error returned was GraphTile NodeInfo index out of bounds: 724724,2,28393 nodecount= 10307.
=> fixed bug where endnode was in another tile

src/thor/pathtest/pathtest.cc
If route fails list any origin and/or destination edges that are marked as unconnected.
=> pathtest update when failure occurs

scripts/batch.sh, scripts/run_city_routes.sh, src/thor/pathtest/pathtest.cc
Possible status cases are:
* __success__ - occurs when route is successful
* __fail_no_route__ - occurs when no route can be found
* __fail_no_connectivity__ - occurs when there is no tile connectivity between origin and destination _only_ if the `--connectivity` flag is passed to pathtest
* __fail_invalid_origin__ - occurs when Loki cannot process origin 
* __fail_invalid_dest__ - occurs when Loki cannot process destination
The statistics.csv file generated by batch.sh now contains a header to help identify values.
=> Added failure cases to pathtest to provide better detail

src/thor/bidirectional_astar.cc, src/thor/pathtest/pathtest.cc, src/thor/service.cc
Fix destination in bidirectional A* (needed to add opposing edge to the adjacency list). Update to TransitionCostReverse call. 
Depends on sif changes
=> Use bidirectional A* for bicycle over 10km.

README.md
Replace "Open Street Map" by "OpenStreetMap"
=> Fix typo in OSM

src/thor/bidirectional_astar.cc, src/thor/multimodal.cc, src/thor/pathalgorithm.cc, src/thor/timedistancematrix.cc, valhalla/thor/pathalgorithm.h, valhalla/thor/timedistancematrix.h
Now the origin edges are not marked as settled/done so a path can come back onto them (around the block
case). This fixes some trivial route cases (begin and end on same edge) that were actually shorter than taking other roads. Removed the special case update_destinations method as this is now done in loki. But SetOrigin and SetDestination have to skip inbound/outbound edges if location is at a node.
=> Remove special case loop and trivial logic. 

src/thor/pathalgorithm.cc, valhalla/thor/pathalgorithm.h
Also pass distance to destination to HandleTransitionEdge (since we already have it and it is accessed several times in the method).
=> Check if end node is in same tile - if so no need to get a new tile.

src/thor/timedistancematrix.cc, valhalla/thor/timedistancematrix.h
Addresses issue #243.
This test exercises the one to many logic with 2 destinations along the same edge as the origin (one before and one after along the oneway edge):
./timedistance_test --json '{"locations":[{"lat":40.038288,"lon":-76.302389},{"lat":40.038204,"lon":-76.303103},{"lat":40.046568,"lon":-76.296479},{"lat":40.027860,"lon":-76.291404},{"lat":40.038389,"lon":-76.301674}],"costing":"auto"}' --config ./conf/planet.json
=> Add logic to handle trivial edge case and "around the block" case.

src/thor/pathtest/pathtest.cc, src/thor/timedistance_test/timedistance_test.cc
Simplify time formatting and include seconds.
=> Use request JSON to override config options. 

src/thor/bidirectional_astar.cc
Was adding incorrect edge to the adjacency list - leading to a case where reverse search is immediately exhausted and forward search can never connect.
Also added a protection in case either direction search is exhausted.
=> Fix error when destination is at a dead-end node.

src/thor/bidirectional_astar.cc
Fix issues with elapsed time on reverse path - one issue was floating point roundoff being accumulated and a bigger issue was incorrectly indexing edges in reverse path (off by one getting secs along an edge). 
Also, if either search is exhausted immediately return no path.
=> Fix elapsed time along reverse path

src/thor/bidirectional_astar.cc
Could not do this within costing since many_to-one would not enter any not_thru regions which a valid origin might reside. This change in conjunction with the sif costing changes effectively results in the same logic.
=> Do not enter not_thru regions in reverse search. 

src/thor/bidirectional_astar.cc, valhalla/thor/bidirectional_astar.h
Apply this to the elapsed time logic in FormPath so the turn cost applies to the correct node. Also look for either temporary or permanently labelled edges when forming candidate connections - this fixes some connections (especially where the paths are in not_thru regions). Add special case logic to FormPath if the forward path connects to a destination edge (can happen when both locations are within the same not-thru region).
=> Separate turn cost in the reverse path. 

src/thor/bidirectional_astar.cc
Fixes an issue with turn costs after transition edges
=> Add opposing edge offset to HandleTransitionEdgeReverse

src/thor/bidirectional_astar.cc
Gives more consistent results.
=> Use cost (not sort cost) to figure which tree to expand.

src/thor/optimizer.cc
It was not set for the case where there are 4 locations and TourCost is called with an indeterminant count_ value.
=> Make sure count_ is set first.

src/thor/bidirectional_astar.cc, src/thor/service.cc
Limit bidirectional A* to 2 passes (never disallow highway transitions) and cut the relaxation factor for bidirectional A*.
=> Switch all but bus to bidirectional A*.

src/thor/bidirectional_astar.cc, valhalla/thor/bidirectional_astar.h
Split turn cost from newcost in forward path to get more accurate cost at the possible connection. Remove unused ModifyHierarchyLimitsReverse method.
=> Add IsBestConnection.

src/thor/multimodal.cc
This with thor updates fixes switching operators, taking buses when not needed, and take a more desired bus route.
<pre><code>
Avoid path example://
<    Depart: 8:05 AM from 23rd Street.
<    VERBAL_DEPART: Depart at 8:05 AM from 23rd Street.
< 4: Take the PATH toward Journal Square. (1 stop) | 0.4 mi
<    VERBAL_PRE: Take the PATH toward Journal Square.
<    VERBAL_POST: Travel 1 stop.
<    Arrive: 8:06 AM at 14th Street.
<    VERBAL_ARRIVE: Arrive at 8:06 AM at 14th Street.
< 5: Transfer at the 6 Av station. | 0.0 mi
<    VERBAL_PRE: Transfer at the 6 Av station.
<    VERBAL_POST: Continue for 20 feet.
<    Depart: 8:06 AM from 6 Av.
<    VERBAL_DEPART: Depart at 8:06 AM from 6 Av.
< 6: Take the L toward CANARSIE - ROCKAWAY PKWY. (9 stops) | 4.2 mi
<    VERBAL_PRE: Take the L toward …
=> added costing for operators

src/thor/multimodal.cc, src/thor/pathalgorithm.cc, src/thor/timedistancematrix.cc
This is an index into a map of operator names. This allows us to compare an operator to the predecessor operator and to add a penalty if not the same.
=> Update EdgeLabels to include an operator index.

src/thor/multimodal.cc, src/thor/trippathbuilder.cc
Add a GetOperatorId method. Update in-station vs. stop-to-stop transfer logic and if in-station make sure a transfer time is added and the departure is still valid (not in the past after adding the transfer time). Wrong value was being added to Adjacency List! Other changes include the way transfer cost is set and an operator change penalty is added.
=> Use correct cost in Adjacency List 

src/thor/trippathbuilder.cc, valhalla/thor/trippathbuilder.h
fixes valhalla/baldr#236
Cannot get directed edge using local edge index when not on the local level. Only get directed edge for intersecting edges when on the local level (use it to set walkability and cyclability of intersecting edges).
=> Fix exception in AddTripIntersectingEdge

src/thor/trip_path.cc, valhalla/thor/service.h
Use bidirectional A* unless origin and destination share an edge.
=> Add get_path_algorithm method.

src/thor/service.cc
This helps lower the long time to fail for some bidirectional routes.
=> Use a lower factor for the expansion within distance.

src/thor/bidirectional_astar.cc
Make sure the reverse A* heuristic is used and that the proper end node is used for the heuristic. Also make sure the opposing edge is set in the EdgeLabel. This fixes the strange bike route (loop) that was reported on Twitter.
=> Fixes to SetDestination. 

scripts/dependencies.sh, scripts/install.sh, src/thor/multimodal.cc
We must get the date from level 3 transit tiles and not level 2.  The level 3 date is set when the fetcher grabbed the transit data and created the schedules.  
Moved prevent going from one transit connection directly to another at a transit stop logic from sif to here.
=> Stupid fingers...ignore branch name.

src/thor/bidirectional_astar.cc, valhalla/thor/bidirectional_astar.h
Extend the searches after an initial connection has been found to allow for connections along long edges. Probably should be based on max edge cost but that reduces performance significantly so use a threshold based on number of iterations. Also - add not_thru edges to EdgeLabels and mark them, but do not add to adjacency list (effectively prunes search but allows connections on them for case where origin and destination connect at a shared node with both entering not_thru edges).
=> Update termination criteria and properly handle not_thru edges.

src/thor/bidirectional_astar.cc, src/thor/trip_path.cc, valhalla/thor/bidirectional_astar.h
Fix not_thru logic. Fix best_connection (use full transition cost with penalties rather than just seconds). Override the not-thru flag on origin/destination to get around the case where a 2 edge loop (e.g. cul-de-sac) has not_thru improperly set.
=> Fixes for best connection

src/thor/costmatrix.cc, valhalla/thor/costmatrix.h
Just update in CostMatrix until better thresholds can be set for bidirectional A*. Add comments and reference to Knopp paper.
=> Update hierarchy limits

src/thor/adjacencylist.cc, src/thor/costmatrix.cc
Also set threshold for a source or target to 0 after calling UpdateStatus so no extra calls are made to expand search in cases where adj. list is exhausted.
=> Fix crash where adj. list current bucket is invalid on a subsequent Remove call.

src/thor/costmatrix.cc
(since unsigned int). This leads to no way to terminate the method.
=> Do not decrement remaining sources or targets if already at 0

src/thor/pathalgorithm.cc
rather than the end node of the directed edge. Fixes #379
=> SetOrigin - if trivial use the origin latlng when finding the A* heuristic

src/thor/pathalgorithm.cc
This constructor is used in TimeDistanceMatrix. Both PathAlgorithm and TimeDistanceMatrix have been largely replaced by BidirectionalAstar and CostMatrix. No sense allocating this memory (which exists in some persistent objects in thor service.
=> Do not reserve EdgeLabels in PathAlgorithm

src/thor/isochrone.cc, valhalla/thor/isochrone.h
this used to leak if you called compute and then didnt delete the thing it gave back. now, no matter what happens it will not leak the computed `isotile`
=> avoid memory leaks

src/thor/matrix.cc
nullptr_t is part of the std namespace. This patch fixes a build error on OpenBSD.
=> nullptr_t → std::nullptr_t

src/thor/multimodal.cc
If use_bus or use_rail is false this will now avoid any lines of that type.
=> Check if a transit directed edge is allowed by the transit costing method

src/thor/service.cc
We cannot set the origin edge to the through edge in this case - we want to remove the through edge and its opposing edge and keep all other edges.
=> Fix an issue with through locations when the location is at a node.

src/thor/trippathbuilder.cc
depends on valhalla/baldr#273
fixes valhalla/odin#352
fixes valhalla/odin#296
``` Diff
< BEFORE
< 1: Drive south on Penwethers Lane. | 0.1 mi
> AFTER
> 1: Drive south on Penwethers Lane. | 0.1 mi
> 2: Turn left to stay on Penwethers Lane. | 0.0 mi
```
=> Added GetOffsetForHeading method that will adjust heading offset based on road class and 'use'

src/thor/costmatrix.cc, src/thor/isochrone.cc, valhalla/thor/costmatrix.h
Try to match the behavior of bidirectional A* (rather than a fixed number of iterations after the first connection has been found). 
Make sure date time is set on origin location for multi-modal isochrones (prevents crash).
=> Use GetThreshold in CostMatrix

src/thor/route_action.cc, src/thor/trippathbuilder.cc
Switch to bidirectional A* for all pedestrian routes.  Updates for trivial cases where the start_pct > end_pct (e.g. reversed travel direction). This is needed for trivial pedestrian routes. Needed to update the start and end percent as well as get the opposing directed edge and update the side of street.
=> Fixes for trivial pedestrian routes

src/thor/bidirectional_astar.cc, src/thor/costmatrix.cc, src/thor/isochrone.cc
Set the not_thru_pruning flag and check that it is true before pruning. Only used for costmatrix and bidirectional.
=> Add support for not_thru

src/thor/costmatrix.cc
CostMatrix is not properly terminating and is taking a longer than normal amount of time for one-to-many requests. This request should take very little time at all since the locations are very close together.
http://localhost:8002/one_to_many?json={%22locations%22:[{%22lat%22:40.744015,%22lon%22:-73.990509},{%22lat%22:40.739735,%22lon%22:-73.979713},{%22lat%22:40.752522,%22lon%22:-73.985016},{%22lat%22:40.750118,%22lon%22:-73.983704},{%22lat%22:40.750553,%22lon%22:-73.993523}]}&costing=auto
=> Fix for costmatrix slowdown for one to many

Makefile.am, src/thor/matrix_action.cc, src/thor/timedistancematrix.cc, valhalla/thor/timedistancematrix.h
Hello Valhalla! Greetings from Navitia! 
As we discussed in this issue: https://github.com/valhalla/thor/issues/408, we have been working on the api `one_to_many` for a couple of days. 
(you're surely aware of all problems of your own baby :laughing: , this is only for the sake of traceability): 
- `one_to_many`/`many_to_one`/`many_to_many` api's `max_locations` is limited to 50 because of the huge demand  in RAM
- Response time is not satisfying for our use case 
As suggested in the  https://github.com/valhalla/thor/issues/408, we try enabling the `timedistancematrix.cc`, and used it only for `one_to_many` api. We noticed that this class is kind of abandoned, some private members and methods are missing, interfaces of outer classes are changed etc..., we did what we can to "repair" this …
=> Enable distancematrix for one to many

src/thor/isochrone_action.cc
builds on valhalla/midgard#107 and valhalla/baldr#314
it clarifies options with respect to the polygons vs linestrings and add generalization as an option
=> make more sane defaults for isochrones and allow for generalization

src/thor/isochrone.cc, src/thor/isochrone_action.cc
fixed a bug where the isochrone was cut off if we took transit that was greater than the max_seconds.
before
after
issue reported by @meghanhade
=> if a bus or rail line goes beyond the max, we need to consider transit options

src/thor/service.cc, src/thor/trace_attributes_action.cc, src/thor/trace_route_action.cc, valhalla/thor/service.h
Reverts valhalla/thor#493
@ericrwolfe the previous PR requires that the request have `trace_options` in it. we need to use get optional so that its not always required to be in the request
=> Revert "Pass custom map-matching parameters to meili"

src/thor/astar.cc, src/thor/bidirectional_astar.cc, src/thor/multimodal.cc, src/thor/service.cc, valhalla/thor/pathalgorithm.h
this uses the number of edge labels added as a metric for when to check if there is an interrupt waiting. in bidirectional astar it seemed that you could get more than one new label at a time so i couldnt use modulus to check it. i basically did that on all the algorithms just in case they were that way too (i figured they werent?)
also note that our code ends up catching the exception that the interrupt throws so we end up actually wasting a bit of time replying to the client. this wasnt supposed to happen but isnt a big deal at all. it can be fixed in the future.
@noblige @dnesbitt61
=> abort path finding if client disconnects (or request times out)
